# watch -n 5 -t -d "curl -s localhost:8080/actuator/prometheus"
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false
            #percentiles-histogram: true
            #percentiles: 0.5, 0.95
spring:
  application:
    name: demo

#wavefront:
#    application:
#        name: demo
#        service: getting-started
